apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: gzaj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gzaj
    app.kubernetes.io/part-of: byoc-app-zots
  name: gzajnjll
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: gzaj
    weight: null
status: {}
